### ISSUE TITLE
Retrieve percentile contrast limit

### ISSUE THREAD

**Issue by Jose-Verdu-Diaz** [haesleinhuepf/napari-brightness-contrast#10]
I'm building an application that integrates napari and this plugin, and it would be very useful to retrieve the contrast percentiles the same way I'm able to obtain the absolute limits:

```
viewer = napari.Viewer()
layer = viewer.add_image(data)
napari.run()
print(layer.contrast_limits)
```

Also, it would be great if I could display the plugin docked when running napari, is it possible to do so?

Thank you for your work!

**Comment by haesleinhuepf** [comment]
> I could display the plugin docked when running napari, is it possible to do so?

The only way that comes to my mind is you actively add the dock widget from your application's main function, e.g. like here:
https://github.com/haesleinhuepf/napari-brightness-contrast/blob/main/napari_brightness_contrast/_tests/test_dock_widget.py#L20-L21

There might be alternatives, the napari developers know. I suggest to ask via https://image.sc , there are plenty of napari developers and users who answer questions very quickly.

> I'm building an application that integrates napari and this plugin, and it would be very useful to retrieve the contrast percentiles the same way I'm able to obtain the absolute limits:

You can also reuse this function to retrieve a histogram from a layer:
https://github.com/haesleinhuepf/napari-brightness-contrast/blob/a7e09f001a584df6e1989c643ad5820517e0c727/napari_brightness_contrast/_dock_widget.py#L324

Using the histogram and the layer's contrast-limits, it should be possible to compute the percentiles that were potentially selected by the user. If you think some of the code might be of interest to a broader audience, feel free to send a pull-request or post it here so. that I can integrate it. Contributions are very welcome!

Thanks for reaching out btw!

Best,
Robert

**Comment by Jose-Verdu-Diaz** [comment]
> The only way that comes to my mind is you actively add the dock widget from your application's main function, e.g. like here:
https://github.com/haesleinhuepf/napari-brightness-contrast/blob/main/napari_brightness_contrast/_tests/test_dock_widget.py#L20-L21

That worked wonders, thank you! 

> Using the histogram and the layer's contrast-limits, it should be possible to compute the percentiles that were potentially selected by the user. If you think some of the code might be of interest to a broader audience, feel free to send a pull-request or post it here so. that I can integrate it. Contributions are very welcome!

One simple way to retrieve the percentile would be the following one: 

```
viewer = napari.Viewer()
layer = viewer.add_image(data)
bc = BrightnessContrast(viewer)
viewer.window.add_dock_widget(bc)
napari.run()

percentile_upper = bc.spinner_upper_percentile.value()
percentile_lower = bc.spinner_lower_percentile.value()

print(f'Upper: {percentile_upper}\nLower: {percentile_lower}')
```

However, this returns a `RuntimeError: wrapped C/C++ object of type QSpinBox has been deleted` error. I'm quite a newbie in napari and Qt, but I imagine it won't be possible to retrieve `bc.spinner_upper_percentile.value()` after closing napari. Ive tried to hook to a napari event and get percentile values before closing napari, without much success:

```
viewer = napari.Viewer()
layer = viewer.add_image(self.channels[opt].image_norm)

bc = BrightnessContrast(viewer)
viewer.window.add_dock_widget(bc)

class Percentiles:
    def __init__(self):
        self.upper = None
        self.lower = None
    
    def update(event):
        self.upper = bc.spinner_upper_percentile.value()
        self.lower = bc.spinner_lower_percentile.value()
        print(f'Upper: {self.upper}\nLower: {self.lower}') # Percentiles saved succesfully

percentiles = Percentiles()
layer.events.connect(callback = percentiles.update)
napari.run()

print(f'Upper: {percentiles.upper}\nLower: {percentiles.lower}') # Percentiles() out of scope when changing values: percentiles are None
```

> I suggest to ask via https://image.sc/ , there are plenty of napari developers and users who answer questions very quickly.

Dind't know about this community, thank you! I will be attending the I2K 2022 conference.

**Comment by Jose-Verdu-Diaz** [comment]
> Ive tried to hook to a napari event and get percentile values before closing napari, without much success:

I got it working! I used the layer metadata property to store percentile values on the event.

```
viewer = napari.Viewer()
layer = viewer.add_image(self.channels[opt].image_norm)

bc = BrightnessContrast(viewer)
viewer.window.add_dock_widget(bc)

layer.metadata = {
    'percentile_upper': bc.spinner_upper_percentile.value(),
    'percentile_lower': bc.spinner_lower_percentile.value()
}
def update(event):
    layer.metadata = {
        'percentile_upper': bc.spinner_upper_percentile.value(),
        'percentile_lower': bc.spinner_lower_percentile.value()
    }

layer.events.connect(callback=update)
napari.run()

print(f'Upper: {metadata["percentile_upper"]}\nLower: {metadata["percentile_lower"]}')
```
