### ISSUE TITLE
Upgrade to copier template

### ISSUE THREAD

**Issue by jnahlers** [haesleinhuepf/napari-brightness-contrast#11]
The [napari-plugin-template](https://github.com/napari/napari-plugin-template) has recently been updated to use [copier](https://copier.readthedocs.io/en/stable/). This will help with updating old plugins, such as this one. As a brightness and contrast plugin is critical for many users of Napari, it would be good to get this plugin up to the latest plugin template standards, which will facilitate further development.

I note that many important (and 'obvious') plugins (with intuitive names) were created early during the development cycle of Napari, and many are now outdated. The change to using copier will make it easier to keep plugins up to date.

**Comment by haesleinhuepf** [comment]
Hey @jnahlers ,



> This will help with updating old plugins, such as this one.

Can you outline how a new template (which are commonly used for setting up new plugins)  can help with updating old plugins?



> many are now outdated.

I'm mot sure what you mean here. Is there anything that doesn't work anymore or bugs you experience?

Thanks for the feedback!

Best,
Robert
